// types
import {
  OrdersPaymentStatusEnum,
  OrdersPaymentTypeEnum,
  OrdersStatusEnum,
  OrdersTypeEnum
} from './ordersTableEnum';
import type { DataType } from './ordersTableType';

export const ordersTableMockData: DataType[] = [
  {
    key: '1',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: true,
    status: OrdersStatusEnum.PENDING,
    type: OrdersTypeEnum.AT_RESTAURANT,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.UNPAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '2',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: true,
    status: OrdersStatusEnum.PENDING,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.ONLINE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '3',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.REJECT,
    type: OrdersTypeEnum.PICKUP,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '4',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.REJECT,
    type: OrdersTypeEnum.IN_STORE_PICKUP,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '5',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '6',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '7',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '8',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '9',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '10',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: true
  },
  {
    key: '11',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: true
  },
  {
    key: '12',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: true
  },
  {
    key: '13',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: true
  },
  {
    key: '14',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '15',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '16',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '17',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '18',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '19',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '20',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '21',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '22',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '23',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  },
  {
    key: '24',
    orderId: 12345,
    email: 'test@gmail.com',
    newOrder: false,
    status: OrdersStatusEnum.CONFIRM,
    type: OrdersTypeEnum.AT_HOME,
    paymentType: OrdersPaymentTypeEnum.IN_PLACE,
    paymentStatus: OrdersPaymentStatusEnum.PAID,
    waiter: 'David',
    cost: 2000,
    utcDateString: 'Sat, 02 Nov 2024 07:00:42 GMT',
    archived: false
  }
];
